package com.example.myunsplashphotosapp.models_Random

data class User_Random(
    val alt_description: String?,
    val alternative_slugs: AlternativeSlugs?,
    val blur_hash: String?,
    val breadcrumbs: List<Any>?,
    val color: String?,
    val created_at: String?,
    val current_user_collections: List<Any>?,
    val description: Any?,
    val downloads: Int?,
    val exif: Exif?,
    val height: Int?,
    val id: String?,
    val liked_by_user: Boolean?,
    val likes: Int?,
    val links: Links?,
    val location: Location?,
    val meta: Meta?,
    val promoted_at: String?,
    val public_domain: Boolean?,
    val slug: String?,
    val sponsorship: Any?,
    val tags: List<Tag>?,
    val tags_preview: List<TagsPreview>?,
    val topic_submissions: TopicSubmissionsXX?,
    val topics: List<Topic>?,
    val updated_at: String?,
    val urls: UrlsXX?,
    val user: UserXX?,
    val views: Int?,
    val width: Int?
)